version: "3.8"

services:
  hm-mysql:
    image: mysql
    container_name: hm-mysql
    ports:
      - "3306:3306"
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: eric
    volumes:
      - "./hm-mysql/conf:/etc/mysql/conf.d"
      - "./hm-mysql/data:/var/lib/mysql"
      - "./hm-mysql/init:/docker-entrypoint-initdb.d"
    networks:
      - hm-net
  hm-hmall:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: hm-hmall
    ports:
      - "8080:8080"
    networks:
      - hm-net
    depends_on:
      - hm-mysql
  hm-nginx:
    image: nginx
    container_name: hm-nginx
    ports:
      - "18080:18080"
      - "18081:18081"
    volumes:
      - "./hm-nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./hm-nginx/html:/usr/share/nginx/html"
    depends_on:
      - hm-hmall
    networks:
      - hm-net
networks:
  hm-net:
    name: hmall